### ISSUE TITLE
Download does not exist

### ISSUE THREAD

**Issue by Starlynk1** [gregsaun/BearExxa-V2#2]
Tried using the download link and it says there is nothing there. Checked for releases as that is where the link is pointing to and no releases. In the process of upgrading from the original Bear 2.0 frame (mk2.5s) and want to do all of it including the v2 exxa.

**Comment by gregsaun** [comment]
Hello, I'm still working on building the repository for the release. This is why there is no release yet and the links are not working. Once the release will be set the link will work. The STL will not change until the release but some documentation and text in the repository will.

I'm closing this one, please reopen if not clear enough.
